### ISSUE TITLE
System.IO.FileNotFoundException when down-targeting to netcoreapp1.0

### ISSUE THREAD

**Issue by jeremymeng** [xunit/xunit#1601]
repro steps
```
dotnet new xunit -o repro
cd repro
notepad repro.csproj
```
change the TargetFramework from `netcoreapp2.0` to `netcoreapp1.0`.  Now the content is

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

</Project>
```
switch back to command prompt and run
```
dotnet restore
dotnet xunit
```

**Actual**:
```
Detecting target frameworks in repro.csproj...
Building for framework netcoreapp1.0...
  repro -> E:\temp\repro\bin\Debug\netcoreapp1.0\repro.dll
Running .NET Core 1.0.5 tests for framework netcoreapp1.0...
xUnit.net Console Runner (64-bit .NET Core 4.0.0.0)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load the specified file.
```

**Note**
`dotnet test` works fine

.NET Core SDK 2.1.3 is used, I have 1.0.5 runtime installed

```
 Directory of E:\Program Files\dotnet\shared\Microsoft.NETCore.App

12/28/2017  10:29 AM    <DIR>          .
12/28/2017  10:29 AM    <DIR>          ..
12/28/2017  09:55 AM    <DIR>          1.0.4
12/28/2017  10:29 AM    <DIR>          1.0.5
12/28/2017  09:55 AM    <DIR>          1.1.1
12/27/2017  04:34 PM    <DIR>          2.0.4
```

**Comment by bradwilson** [comment]
I'm unable to reproduce the issue:

![image](https://user-images.githubusercontent.com/16944/34424159-4e07cde0-ebd6-11e7-834a-d965289fdb24.png)

**Comment by jeremymeng** [comment]
It must be some machine/configuration difference. It originally happened in this appveyor PR build: https://ci.appveyor.com/project/StackExchange/stackexchange-redis/build/1.0.504

**Comment by bradwilson** [comment]
Verified that this is already fixed in `2.4.0-beta1-build3907`.

**Comment by bradwilson** [comment]
This appears to be somehow related to the presence (or absence) of `xunit.runner.visualstudio`; then it's present, everything works (and when absent, everything fails).

At this point in time, I have no idea why that might be. The difference between the `.deps.json` files does not indicate anything out of the expected.

**Comment by bradwilson** [comment]
So, in case it isn't clear: anybody who is experiencing this problem only needs to add the `xunit.runner.visualstudio` package (as well as using `2.4.0-beta1-build3907` or later) to resolve the issue.

**Comment by VictorioBerra** [comment]
Using 2.4.0-beta.1.build3958 did not solve the issue for me.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.4.0-beta.1.build3958" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0-beta.1.build3958" />
  </ItemGroup>

</Project>
```

Command used to execute tests:

` C:/SourceCode/MyApp/tools/xunit.runner.console.2.4.0-beta.1.build3958/tools/netcoreapp1.0/xunit.console.dll "C:/SourceCode/MyApp/tests/MyApp.UnitTests/bin/Release/netcoreapp2.0/LifecycleManager.UnitTests.dll" -xml "artifacts/testresults/results.xml"`

**Comment by bradwilson** [comment]
@VictorioBerra Please open a new issue with a repro project.

**Comment by VictorioBerra** [comment]
@bradwilson My issue was that I was trying to use `xunit.runner.console.2.3.1\tools\netcoreapp1.0` to run a netcoreapp2.0 test library. I missed it because of my cake file strings.

**Comment by NickCraver** [comment]
Is there any chance of merging #1643 in? We can't use the 2.4.0 beta because of the issue there, and 2.3.1 breaks due to the issue here - AFAIK there's no build available for which all tests run (since MyGet was cleared a while back).

**Comment by bradwilson** [comment]
Closing for age and that it appears to no longer be relevant.
