### ISSUE TITLE
XUnit.V3 version compatible to MTP 2.0.0

### ISSUE THREAD

**Issue by Lorilatschki** [xunit/xunit#3416]
We are currently updating to MTP 2.0.0 for one of our testing extensions. Since we are using `xunit.v3` across our whole code base, we need a compatible version of `xunit.v3`. Otherwise we run into the following runtime issue:

```log
Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.Testing.Platform.Extensions.TestHost.IDataConsumer' from assembly 'Microsoft.Testing.Platform, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Testing.Platform.MSBuild.MSBuildExtensions.AddMSBuild(ITestApplicationBuilder builder)
   at Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook.AddExtensions(ITestApplicationBuilder testApplicationBuilder, String[] _) in /_/src/Platform/Microsoft.Testing.Extensions.MSBuild/TestingPlatformBuilderHook.cs:line 19
   at Saucery.Core.Tests.SelfRegisteredExtensions.AddSelfRegisteredExtensions(ITestApplicationBuilder builder, String[] args) in /home/runner/work/Saucery/Saucery/Saucery.Core.Tests/obj/Release/net9.0/SelfRegisteredExtensions.cs:line 14
   at Saucery.Core.Tests.MicrosoftTestingPlatformEntryPoint.Main(String[] args) in /home/runner/work/Saucery/Saucery.Core.Tests/obj/Release/net9.0/MicrosoftTestingPlatformEntryPoint.cs:line 14
   at Saucery.Core.Tests.MicrosoftTestingPlatformEntryPoint.<Main>(String[] args)
```

Can you please provide a version which refers to `Microsoft.Testing.Platform` v2.0.0.

**Comment by agray** [comment]
https://github.com/microsoft/testfx/issues/6686

**Comment by bradwilson** [comment]
We have opted to delay our support for MTP v2 due to technical limitations with the interactions with .NET 10 SDK. We have no planned release date at this time.

**Comment by Lorilatschki** [comment]
@bradwilson thanks for the quick reply.

**Comment by asarkar** [comment]
@Lorilatschki I'm using xUnit 3.1.0 with .NET 10.0.100-rc.2 in a personal project, and not seeing this issue. Is it triggered by code coverage?

**Comment by jcasale** [comment]
It only happens when you explicitly opt in to use the `Microsoft.Testing.Platform` v2.0 runner, see [Migrate from VSTest to Microsoft.Testing.Platform](https://learn.microsoft.com/en-us/dotnet/core/testing/migrating-vstest-microsoft-testing-platform).

**Comment by asarkar** [comment]
@jcasale I've both of the following, and still no error.

Directory.Build.props
```
<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
```
global.json
```
{
  "test": {
    "runner": "Microsoft.Testing.Platform"
  }
}
```

My project is [here](https://github.com/asarkar/functional-csharp-buonanno).

**Comment by jcasale** [comment]
You're not using `Microsoft.Testing.Platform` v2.0, your solution, in its current configuration, takes out a transitive dependency on v1.8.4.

Manually install it, then run `dotnet run --project tests\Ch02.Tests\Ch02.Tests.csproj` for example, and you'll experience the behavior.

**Comment by bradwilson** [comment]
This is all expected behavior:

* Using MTP 1.x (with version of .NET SDK, including .NET 10 SDK) works fine.
* Using MTP 2.x (with any version of .NET SDK) is not currently supported.

**Comment by bradwilson** [comment]
MTP v2 is now supported as of v3 `3.1.1-pre.9` https://xunit.net/docs/using-ci-builds

-----

With this build, we support three MTP modes: "off", "v1", and "v2". For compatibility reasons, the default is "v1".

Including the `xunit.v3` (or `xunit.v3.core`) NuGet package gets you "v1". If you want "off" or "v2", you must specify a custom version of `xunit.v3` (or `xunit.v3.core`).

- If you're using `xunit.v3`, replace it with either `xunit.v3.mtp-off` or `xunit.v3.mtp-v2`.
- If you're using `xunit.v3.core`, replace it with either `xunit.v3.core.mtp-off` or `xunit.v3.core.mtp-v2`.

For parity purposes, we are also shipping `xunit.v3.mtp-v1` (and `xunit.v3.core.mtp-v1`) so that you can specify you want v1 even if the default later changes to v2. We would likely consider this a breaking change given MTP v2's interaction differences with .NET 10 SDK. Starting with this build, referencing `xunit.v3` (or `xunit.v3.core`) simply references `xunit.v3.mtp-v1` (or `xunit.v3.core.mtp-v1`) for you. It is currently undecided how long we will maintain support for MTP v1, at least in part because we don't know how long Microsoft plans to support MTP v1.

Finally, setting `<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>` will generate a build error if you reference `xunit.v3.core.mtp-off` (directly or indirectly), for what I hope are obvious reasons. 😀

The documentation pages will be updated once this ships into RTM.

-----

This build also includes a breaking change to internal types. Since these types are internal, we are not marking this is a breaking change in the NuGet package version.

The MTP support types have moved from the `Xunit.Runner.InProc.SystemConsole.TestingPlatform` namespace (in `xunit.v3.runner.inproc.console.dll`) to the `Xunit.MicrosoftTestingPlatform` namespace (in `xunit.v3.mtp-v1.dll` and `xunit.v3.mtp-v2.dll`). If you are referencing any of these types, you will need to use the new namespace. Note that there is no separate package for these assemblies; they are shipped inside of the `xunit.v3.core.mtp-v1` and `xunit.v3.core.mtp-v2` NuGet packages.

By necessity, this also changes the auto-generated entrypoints, since they call `TestPlatformTestFramework` (from the affected namespace). If you were using the `<XunitAutoGeneratedEntryPoint>false</XunitAutoGeneratedEntryPoint>` (which is undocumented and unsupported) to inject your own entrypoint, and wish to continue supporting MTP, then your entrypoint will need to use the new namespace rather than the old namespace.

**Comment by asarkar** [comment]
@bradwilson Thank you for the update. To ease migration, would you also consider releasing `xunit.v3.mtp-v2` (along with the `v1` and `off` variations) meta package so that the single `xunit.v3` doesn't need to be replaced by 3 separate packages, 2 of which are seemingly unrelated to mtp-v2?

**Comment by bradwilson** [comment]
Yes, I'll consider this.

**Comment by bradwilson** [comment]
I've pushed the new packages with `3.1.1-pre.9` and updated the instructions above.

**Comment by Lorilatschki** [comment]
@bradwilson thanks for the fast support! 
Through renovate and the `replacementName` feature, the migration to `xunit.v3.mtp-v2` or `xunit.v3.mtp-v1` can be done automatically.

```json
{
  "matchCurrentVersion": ">=3.1.0",
  "matchDatasources": [
	"nuget"
  ],
  "matchPackageNames": [
	"xunit.v3"
  ],
  "replacementName": "xunit.v3.mtp-v2",
  "replacementVersion": "3.2.0"
}
{
  "matchCurrentVersion": ">=3.1.0",
  "matchDatasources": [
	"nuget"
  ],
  "matchPackageNames": [
	"xunit.v3.core"
  ],
  "replacementName": "xunit.v3.core.mtp-v2",
  "replacementVersion": "3.2.0"
}
```

BTW: The mentioned new package names are not yet available via [www.nuget.org](https://www.nuget.org/packages/xunit.v3), instead only via https://feedz.io/org/xunit/repository/xunit/search. When will they be available via nuget.org?0

**Comment by bradwilson** [comment]
> When will they be available via nuget.org?

I don't have a planned release date for 3.1.1 yet. All that's there right now is really just one bug fix and this. That said, it has been a month since the last release, so I'll poke around the issues and see if there are some low hanging fruit I can address to fill out an official release.

**Comment by Lorilatschki** [comment]
I am just asking, because I saw some pre release versions on nuget.org already. For our environment the nuget feed is mandetory.

**Comment by bradwilson** [comment]
Our current policy is to only provide prerelease versions on NuGet for major versions so they can be tested for the impact of breaking changes.

**Comment by Lorilatschki** [comment]
Thanks for the feedback.

**Comment by julealgon** [comment]
> I don't have a planned release date for 3.1.1 yet. All that's there right now is really just one bug fix and this.

Why is this _massive_ fix not enough though? Why are you looking to "fill" the release before getting it out? That makes no sense to me unless your deployment process is incredibly complex and require some unusual manual effort to do.

**Comment by bradwilson** [comment]
Thanks for the feedback on your opinion of the value of this fix.

The release process typically takes me a few hours of effort.

**Comment by julealgon** [comment]
> The release process typically takes me a few hours of effort.

Oh... ok, that's what I feared then. I understand why you prefer bundling up extra changes in that case.

**Comment by agray** [comment]
Updated to xunit.v3 3.2.0 this morning.  Tests ran.

If I THEN update my test project dependency on  Microsoft.Testing.Extensions.CodeCoverage from 18.0.4 to 18.1.0 I get:

```
Building Test Projects
Starting test discovery for requested test run
========== Starting test discovery ==========
[Merlin.XUnit3.dll] Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.Testing.Platform.Extensions.TestHost.IDataConsumer' from assembly 'Microsoft.Testing.Platform, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Testing.Platform.MSBuild.MSBuildExtensions.AddMSBuild(ITestApplicationBuilder builder)
   at Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook.AddExtensions(ITestApplicationBuilder testApplicationBuilder, String[] _) in /_/src/Platform/Microsoft.Testing.Extensions.MSBuild/TestingPlatformBuilderHook.cs:line 19
   at Merlin.XUnit3.SelfRegisteredExtensions.AddSelfRegisteredExtensions(ITestApplicationBuilder builder, String[] args) in C:\gitrepos\Saucery\Merlin.XUnit3\obj\Debug\net9.0\SelfRegisteredExtensions.cs:line 14
   at Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(String[] args, Action`2 extensionRegistration) in /_/src/common/MicrosoftTestingPlatform/TestPlatformTestFramework.cs:line 258
   at Merlin.XUnit3.AutoGenerated.XunitAutoGeneratedEntryPoint.Main(String[] args) in C:\gitrepos\Saucery\Merlin.XUnit3\obj\Debug\net9.0\XunitAutoGeneratedEntryPoint.cs:line 13

========== Test discovery aborted: 0 Tests found in 3.4 sec ==========
========== Starting test run ==========
```

Here is my project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Saucery.Core\Saucery.Core.csproj" />
    <ProjectReference Include="..\Saucery.Tests.Common\Saucery.Tests.Common.csproj" />
    <ProjectReference Include="..\Saucery.XUnit3\Saucery.XUnit3.csproj" />
  </ItemGroup>

</Project>
```

Is this supported with 3.2.0 yet?

**Comment by Lorilatschki** [comment]
It is supported, but you need to switch to [xunit.v3.mtp-v2](https://www.nuget.org/packages/xunit.v3.mtp-v2).

**Comment by agray** [comment]
> It is supported, but you need to switch to [xunit.v3.mtp-v2](https://www.nuget.org/packages/xunit.v3.mtp-v2).

Will it be be integrated in the main package?

**Comment by Lorilatschki** [comment]
As @bradwilson mentioned:
> With this build, we support three MTP modes: "off", "v1", and "v2". For compatibility reasons, the default is "v1".

Currently the main package has the default build against MTP v1. You need to use the `xunit.v3.mtp-v2` until the `xunit.v3` has switched to MTP v2 by default.

**Comment by bradwilson** [comment]
> > It is supported, but you need to switch to [xunit.v3.mtp-v2](https://www.nuget.org/packages/xunit.v3.mtp-v2).
> 
> Will it be be integrated in the main package?

We have no timeline for if/when v2 becomes the default. For the foreseeable future, v1 will be the default, for backward compatibility (and because v2 + .NET 10 SDK purposefully breaks compatibility with people who need to use VSTest from `dotnet test`, which I felt was far too big a breaking change to allow v2 to become the default). In fact it's fair to say this compatibility issue was the primary driver for why I released this feature this way.

**Comment by alexTr3** [comment]
I have a "A runnable project should target a runnable TFM (for instance, net10.0) and have OutputType 'Exe'." because I have "Core projects use by my tests projects" with xunit.v3.extensibility.core ... do you plan to have a xunit.v3.extensibility.core-mtp2?

what should I do?

**Comment by bradwilson** [comment]
There is no need for MTP variants of the core DLL in `xunit.v3.extensibility.core` because the MTP enablement has no impact on the core DLL itself; instead, it is impacted via MSBuild to inject MTP support into the stand-alone executable (by linking in DLLs and changing the entrypoint auto-generation).

Anybody who targets `xunit.v3.extensibility.core` can implicitly support any version of MTP (or MTP being disabled), because the developer chooses which `xunit.v3` (or `xunit.v3.core`) version is appropriate for them, all of which reference the singular `xunit.v3.extensibility.core`.

If you intend to write an extension that _also_ references MTP, then it's up to you to provide versions that are linked against MTP v1 vs. MTP v2 (if you intend to support both), and thus inform your users which variant(s) of `xunit.v3`/`xunit.v3.core` are compatible with which variant(s) of your extension.

**Comment by alexTr3** [comment]
thx for the reply, but using "dotnet test" on the solution, I still have the error A runnable project should target a runnable TFM on the core projects having xunit.v3.extensibility.core.. I don't really want to create an extension. I just want a core test project used by all other test project.. the only way was to use xunit.v3.extensibility.core

I dont want these core projects to be "executable tests", it's class libraries to be used by the other tests projects.. 

what should I do.. 

also, can i fully remove xunit.runner.json?

**Comment by alexTr3** [comment]
Also since you are here, I really need a way to share data across test assemblies.. 

Do you have anything plan or in place to do that? It would be really nice to have this integrated in xunit.. some type of shared concurrent dictionary<string, object> across test assemblies would be perfect.

I can roll out my own using a memorymappedfile but I think it would be useful to have it in the framework..

**Comment by bradwilson** [comment]
If you're using our templates, then using `xunit3-extension` gives a result like this:

<img width="1122" height="1289" alt="Image" src="https://github.com/user-attachments/assets/d4a2b874-7e81-4bc5-a872-8991ede2bc03" />

As you can see, no mention of "runnable TFM" or "OutputType" and the project is targeting `netstandard2.0`. The only way you can get that is if you're linked against one of the `xunit.v3.core` variants (directly or indirectly).

**Comment by bradwilson** [comment]
> Also since you are here, I really need a way to share data across test assemblies

We have no built-in support for this and no plans to add any at this time. In many/most situations, we don't even know if multiple assemblies are being run at the same time, since that information would be hidden from us by VSTest or Microsoft Testing Platform.

There might be an extension out in the wild for this, but I'm skeptical. I think you're going to have to roll your own.

**Comment by alexTr3** [comment]
ok thx I will look at your template.. my core projects are in .net 10 tho.. 

yes we would need a memorymappedfile or something of the sort.. But it would be very useful for sharing test containers.. I'll roll my own and let you know..

**Comment by alexTr3** [comment]
In your template you still have the xunit.runner.json.. is this still needed with mtp-v2?

you also have 
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
  <PackageReference Include="xunit.v3" Version="3.2.0" />
  <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />

from the doc xunit.runner.visualstudio and Microsoft.NET.Test.Sdk can be removed.. 

--
also I would need to be able to have a specific number of thread running "per assembly" is that possible? 

Ex. if max-threads would be 4 and thread per assembly would be 1... only 4 test assembly at a time would be running in parallel, each one with one thread, running each test one after the other..

**Comment by bradwilson** [comment]
> In your template you still have the xunit.runner.json..

This is only in the xunit3 template, not the xunit3-extension template, as this configuration file is only useful for people who are writing & running tests, not people who are writing extensions.

> is this still needed with mtp-v2?

It's the only configuration file that's supported regardless of the runner. If you want to switch to `testconfig.json` (from MTP) then just be aware that those values will only be applied when your test is run with MTP. If you run with VSTest, run with our 1st party runners, or run the test app directly (without turning on the MTP experience), those config file values will be ignored.

> from the doc xunit.runner.visualstudio and Microsoft.NET.Test.Sdk can be removed

This is true if you don't need support for VSTest.

> Ex. if max-threads would be 4 and thread per assembly would be 1... only 4 test assembly at a time would be running in parallel, each one with one thread, running each test one after the other

No, this level of control is not possible because, as previously mentioned, we have no insight into whether multiple test assemblies are running or not when we aren't in control of the runner. The best you could do is configure each test assembly for `maxParallelThreads` of `1`, and then find a way to run the four assemblies in parallel (how to do this is up to your runner in question, and would be documented on their site, not this one).

**Comment by alexTr3** [comment]
So you know I found the problem related to my core test projects doing a A runnable project should target a runnable TFM on dotnet test..

the reason is I had these package in my core project
   ```
<PackageReference Include="Microsoft.Testing.Extensions.CrashDump" Version="2.0.2" />
   <PackageReference Include="Microsoft.Testing.Extensions.HangDump" Version="2.0.2" />
   <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.2" />
   <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.0.2" />
```

I guess these should be in the executable test project only.

**Comment by alexTr3** [comment]
> No, this level of control is not possible because, as previously mentioned, we have no insight into whether multiple test assemblies are running or not when we aren't in control of the runner. The best you could do is configure each test assembly for `maxParallelThreads` of `1`, and then find a way to run the four assemblies in parallel (how to do this is up to your runner in question, and would be documented on their site, not this one).

yes this is an option, so I could run test projects in parallel in a script and limit the max parallelthread .. interesting =) thx

**Comment by bradwilson** [comment]
> I guess these should be in the executable test project only.

In particular, it was likely `Microsoft.Testing.Platform.MSBuild`, since the purpose of this package is to make test projects buildable. There's definitely no reason an extensibility project should be referencing this.

As for the others, I _presume_ MTP extensions are mostly designed to be referenced by test projects and not extensibility projects, but I'm not familiar enough with these to say one way or another whether the references are appropriate/legal.

**Comment by Youssef1313** [comment]
All the mentioned packages above bring the core Microsoft.Testing.Platform package transitively.
Microsoft.Testing.Platform package will set IsTestingPlatformApplication, and in that case the project is recognized by `dotnet test` as "runnable test project". If it's not, we produce an error.

All those packages are really only intended to be referenced by actual test projects, not test utility libraries.

If you really know what you are doing and you really need those packages for non-test projects for any reason, you can then manually set IsTestingPlatformApplication to false. But in most cases you shouldn't really need these packages for non-test projects in the first place.

**Comment by julealgon** [comment]
@Youssef1313 you do realize that this is confusing and somewhat nonstandard, correct? I hope the upcoming Testing SDK will put an end to this type of "magic" on some of these packages and these kinds of assumptions are not necessary anymore.

Yes, leveraging something like `Directory.Build.props` is preferred for adding these packages to multiple projects at once without duplication, but you need to also realize that some people will prefer creating a "Shared" project, add the packages to that, and then consume that "Shared" project as a "bundle" as a means to centralize/reduce duplication. "Normal" library packages will work completely fine using that approach so it is fairly unintuitive that the MTP extension packages cause problems when handled that way.

I think I mentioned in one of the MTP threads how much I personally dislike this MSBuild magic that is happening with some of MTP, and this is yet another reason why it is less than ideal IMHO.

**Comment by bradwilson** [comment]
In fairness to MTP, this was already a problem with xUnit.net v3 before we added MTP support, because of the stand-alone executable design. Needing to auto-inject code into the project means _some_ form of magic, whether through MSBuild tasks or Roslyn code generators, which means you need some way to turn off the magic. This is true for us even if you go down the "no MTP" path that we just introduced.

In our case all the way back in v2, we split "core" (for testing) from "extensibility" (for extending), and so our recommendation would be for the common project to pull in the extensibility references, and the actual test projects to pull in the core references. The "consequences" back in v2 were much less severe for pulling "core" into a project which you didn't actually intend to run, but they're much more "in your face" now for v3.
