### ISSUE TITLE
Lazy F# test functions with commas report incorrect stack trace

### ISSUE THREAD

**Issue by ploeh** [xunit/xunit#440]
In F#, you can give functions names with white space, punctuation, etc. using double backticks:

```F#
let ``This is my function`` () = ()
```

The name of the function is "This is my function", complete with spaces. You can also use other unusual characters, such as commas:

```F#
[<Fact>]
let ``fact,Normal`` () = 1 / 0
```

The above function has a comma in its name, and always fails with a `DivideByZeroException`. So far, all is good.

# Lazy tests, no commas

You can also write a test that contains a lazy evaluation:

```F#
[<Fact>]
let ``fact Lazy`` () = (lazy (1 / 0)).Value
```

This wraps the division by zero in a lazy computation, and then forces evaluation by accessing its `Value`. Obviously, we expect this to fail, and it does:

![image](https://cloud.githubusercontent.com/assets/242165/8266636/9adef3a6-1739-11e5-890b-1d3b92c1dde5.png)

As you can see from this screen shot from the Visual Studio Test Runner, the stack trace contains two clickable locations. This is to be expected, because the exception is thrown from the expression within the lazy computation, and then again when accessing the `Value`. In this degenerate example, these locations are both of the same line of code, but this doesn't have to be the case at all. In fact, I originally discovered the behaviour described below exactly because I had these parts spread out - in fact, the lazy evaluation was done by FsCheck.

All is still good.

# Lazy tests with commas

Now change the above test by replacing the space in the name with a comma:

```F#
[<Fact>]
let ``fact,Lazy`` () = (lazy (1 / 0)).Value
```

When I run this, I get this result:

![image](https://cloud.githubusercontent.com/assets/242165/8266666/7e186e76-173b-11e5-8c5a-613f6c866f3b.png)

Notice that the top entry in the stack trace is no longer clickable, and also strangely formatted.

# Further observations

Here, I've chosen to represent the problem with screen shots from the Visual Studio Test Runner. One strange observation is that if I right-click on the test error and click **Copy All**, I get a text representation of the error.

When I compare the two errors, I can't discern what would cause one of them to be correctly formatted, but the other one incorrectly formatted.

This is further compounded by looking at the output from the console runner:

```
$ packages/xunit.runner.console.2.0.0/tools/xunit.console.exe Library2/bin/Debug/Library2.dll
xUnit.net console test runner (64-bit .NET 4.0.30319.34209)
Copyright (C) 2015 Outercurve Foundation.

Discovering: Library2
Discovered:  Library2
Starting:    Library2
   Repro.fact Lazy [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
         Library2\Library1.fs(11,0): at Repro.fact Lazy@11.Invoke(Unit unitVar)
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
         Library2\Library1.fs(11,0): at Repro.fact Lazy()
   Repro.fact,Lazy [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
         Library2\Library1.fs(14,0): at Repro.fact\,Lazy@14.Invoke(Unit unitVar)
            at System.Lazy`1.CreateValue()
            at System.Lazy`1.LazyInitValue()
         Library2\Library1.fs(14,0): at Repro.fact,Lazy()
   Repro.fact,Normal [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
         Library2\Library1.fs(8,0): at Repro.fact,Normal()
Finished:    Library2

=== TEST EXECUTION SUMMARY ===
   Library2  Total: 3, Errors: 0, Failed: 3, Skipped: 0, Time: 0,281s
```

If there's a difference in formatting, I can't see it.

This would seem to indicate a bug in the Visual Studio Test Runner, but if you run the tests with the [TestDriven.Net](http://testdriven.net) Visual Studio add-in, you can see the problem here as well:

```
------ Test started: Assembly: Library2.dll ------

Test 'Repro.fact Lazy' failed: System.DivideByZeroException : Attempted to divide by zero.
	c:\Users\Mark\Desktop\Library2\Library2\Library1.fs(11,0): at Repro.fact Lazy@11.Invoke(Unit unitVar)
	at System.Lazy`1.CreateValue()
	at System.Lazy`1.LazyInitValue()
	at System.Lazy`1.get_Value()
	c:\Users\Mark\Desktop\Library2\Library2\Library1.fs(11,0): at Repro.fact Lazy()

Test 'Repro.fact,Lazy' failed: System.DivideByZeroException : Attempted to divide by zero.
	   at Repro.fact\,Lazy@14.Invoke(Unit unitVar) in c:\Users\Mark\Desktop\Library2\Library2\Library1.fs:line 14
	at System.Lazy`1.CreateValue()
	at System.Lazy`1.LazyInitValue()
	at System.Lazy`1.get_Value()
	c:\Users\Mark\Desktop\Library2\Library2\Library1.fs(14,0): at Repro.fact,Lazy()

Test 'Repro.fact,Normal' failed: System.DivideByZeroException : Attempted to divide by zero.
	c:\Users\Mark\Desktop\Library2\Library2\Library1.fs(8,0): at Repro.fact,Normal()

0 passed, 3 failed, 0 skipped, took 0,95 seconds (xUnit.net 2.0.0 build 2929).
```

This may seem like quite a ridiculous and insignificant problem, but I originally discovered it in some of my [FsCheck](https://github.com/fscheck/FsCheck) properties (tests).

First, I spent a couple of hours attempting to hunt down the bug in FsCheck, until I realised that I could reproduce it with vanilla xUnit.net.

Then I thought it was a bug in TestDriven.Net, until I realised that it also manifests itself in the Visual Studio Test Runner.

Subsequently I used a couple of hours attempting to hunt down the reason looking through the xUnit.Net code base, but didn't feel enlightened.

Before I use more time and energy on this, I wanted to ask about this issue here. When stuck, it sometimes helps to ask for help :smile:

**Comment by bradwilson** [comment]
Thanks for the extremely detailed repro. I admit to not really knowing how this is happening, but we can look into it.

**Comment by bradwilson** [comment]
I'm not sure what version of Visual Studio you're using, but for me with VS 2015 RC and xUnit.net 2.1 Beta 3, I'm not able to reproduce either issue. I'm not sure if this was fixed by xUnit.net, or fixed by F# 4.0.

![F# Visual Studio runner](https://cloud.githubusercontent.com/assets/16944/8502781/08b23ca0-216a-11e5-97b2-5445e5e68738.png)

```
$ .\packages\xunit.runner.console.2.1.0-beta3-build3029\tools\xunit.console.exe .\v2_net45_FSharp\bin\Debug\v2_net45_FSharp.dll
xUnit.net Console Runner (64-bit .NET 4.0.30319.0)
  Discovering: v2_net45_FSharp (method display = ClassAndMethod, parallel test collections = on, max threads = 8)
  Discovered:  v2_net45_FSharp (running 1 test case)
  Starting:    v2_net45_FSharp
    FSharp.BasicTests.fact,Lazy [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
        v2_net45_FSharp\BasicTests.fs(7,0): at <StartupCode$v2_net45_FSharp>.$BasicTests.clo@7.Invoke(Unit unitVar)
           at System.Lazy`1.CreateValue()
           at System.Lazy`1.LazyInitValue()
        v2_net45_FSharp\BasicTests.fs(7,0): at FSharp.BasicTests.fact,Lazy()
  Finished:    v2_net45_FSharp
=== TEST EXECUTION SUMMARY ===
   v2_net45_FSharp  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.121s
```

**Comment by ploeh** [comment]
This is on Visual Studio 2013, Windows 7.

Culture (could actually be important, since *comma* is the decimal separator here): da-DK

**Comment by bradwilson** [comment]
What version of xUnit.net? If you're using 2.x, can you please try with 2.1 Beta 3 and see if the problem is solved?

**Comment by ploeh** [comment]
As reported, this was on xunit.core 2.0.0.

I've attempted to try with 2.1 beta 3, but this isn't possible:

```
> Get-Package
No packages installed.
> Install-Package xunit.core -Pre
Attempting to resolve dependency 'xunit.extensibility.core (= 2.1.0-beta3-build3029)'.
Attempting to resolve dependency 'xunit.abstractions (= 2.0.0)'.
Install-Package : 'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.
At line:1 char:1
+ Install-Package xunit.core -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> Get-Package
No packages installed.
```

**Comment by bradwilson** [comment]
> Install-Package : 'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.

You need to upgrade to the latest available NuGet package manager.

**Comment by ploeh** [comment]
The version I'm using is 2.8.50926.663. AFAICT, it's the [latest stable version](http://docs.nuget.org).

**Comment by bradwilson** [comment]
That build is 10 months old, and 6 months older than the latest build for VS 2013.

![NuGet Package Manager in VS 2013](https://cloud.githubusercontent.com/assets/16944/8516043/46826366-2363-11e5-9551-83f3555b1a2f.png)

**Comment by bradwilson** [comment]
BTW, the `50926` part of the build is the date when it was built (September 26th of last year). You should not assume that `2.8.5xxxx` means that you have 2.8.5.

**Comment by ploeh** [comment]
Oh, weird that VS hadn't told me about that update, but almost as if on cue, it presented me with a handful of updates, where NuGet was one of them. I've now updated NuGet, and was also able to update xUnit.net:

```
> Get-Package | ft -AutoSize

Id                        Version               Description/Release Notes                                                                                                      
--                        -------               -------------------------                                                                                                      
xunit.abstractions        2.0.0                 Common abstractions used to exchange information between xUnit.net and version-independent runners (xunit.abstractions.dll)....
xunit.core                2.1.0-beta3-build3029 Includes the libraries for writing unit tests with xUnit.net....                                                               
xunit.extensibility.core  2.1.0-beta3-build3029 Includes xunit.core.dll for extensibility purposes....                                                                         
xunit.runner.console      2.1.0-beta3-build3029 Console runner for the xUnit.net framework. Capable of running xUnit.net v1.9.2 and v2.0+ tests.                               
xunit.runner.visualstudio 2.1.0-beta3-build1069 Visual Studio 2012+ Test Explorer runner for the xUnit.net framework. Capable of running xUnit.net v1.9.2 and v2.0+ tests.
```

However, the behaviour remains the same as originally reported.

**Comment by bradwilson** [comment]
Alright, I'll see if I can repro this on 2013, since that seems to be the only remaining variable (in which case, it's probably an F# bug that has been fixed, that I can do nothing about).

**Comment by ploeh** [comment]
> it's probably an F# bug

My bet is on a localization bug.

FWIW, this isn't a big deal for me, so if it's very difficult to resolve, I'll just keep working around it. I just found it odd when I originally encountered this behaviour, and thought I'd better report it - just in case :smile:

**Comment by bradwilson** [comment]
I'm still not able to repro this in VS 2013 Update 4 + F# 3.1.2. I created a brand new F# class library and I'm using the same references as you:

```
PM> Get-Package | Select Id, Version | ft -AutoSize

Id                        Version              
--                        -------              
xunit.abstractions        2.0.0                
xunit.core                2.1.0-beta3-build3029
xunit.extensibility.core  2.1.0-beta3-build3029
xunit.runner.visualstudio 2.1.0-beta3-build1069
```

With this code:

```fsharp
namespace FSharpTests

type Class1() = 
    [<Xunit.Fact>]
    let ``fact,Lazy`` () = (lazy (1 / 0)).Value
```

And the failure stack trace is correctly rendered and clickable:

![Visual Studio Runner](https://cloud.githubusercontent.com/assets/16944/8583960/9c10cd7a-2586-11e5-9fa6-1000c171be6a.png)

So, I'm at a loss as to what's causing your issue. :(

**Comment by ploeh** [comment]
FWIW, I can (re)produce this issue on two different machines (one Win 7, and one Win 8), but I have no idea what causes it. I tried to change my localization settings to `en-US`, but the issue remains, so it no longer looks quite so much as a localization issue as I previously thought.

This may be too localized, so perhaps we should close this issue.

**Comment by bradwilson** [comment]
I agree. I would like to know what it is, but at this point I'm pretty convinced that it's not xUnit.net's doing. :neutral_face:
