### ISSUE TITLE
Support for custom test discovery and app domains?

### ISSUE THREAD

**Issue by JunTaoLuo** [xunit/xunit#750]
I ran into an issue using `xunit.runner.console` and custom test discovery in our testing infrastructure. After a brief search I stumbled on https://github.com/xunit/xunit/issues/669 where I noticed the suggested workaround of disabling app domains in order to allow remoting, required by custom discovery and execution, to work correctly. However, to run our tests, we also require binding redirects which I believe won't work when we turn off app domains.

In this scenario, is there a suggested method of implementing custom test discovery and execution and still maintaining app domains?

cc @victorhurdugaci @pakrym @davidfowl

**Comment by bradwilson** [comment]
It's hard to know what problem you're having because you don't provide a repro.

In general, extensibility via `xunit.execution.desktop.dll` should just work. The referenced bug was regarding extensibility via `xunit.execution.dotnet.dll` was giving him troubles (for the console runner, this bug was fixed in 2.2 beta 1, because it forces app domains off when it realizes you're linked against `dotnet` instead of `desktop`).

Note that for extensibility, you MUST ship two separate libraries if you plan to target `desktop` and `dotnet`, because the execution library is not a PCL. If this is the path you're going down, then you should look at the way @AArnott has set up his project, because you'll need to do the same thing.

**Comment by bradwilson** [comment]
BTW, when you say "desktop" runner, I assume you realize that the use of `xunit.runner.console` for DNX project is not a tested or supported scenario.

**Comment by natemcmaster** [comment]
Here is a repro for 2.1.0 https://gist.github.com/natemcmaster/373d69057075589c979c. 2.2.0-beta1 appears to have resolved the issue for xunit.runner.console, but xunit.runner.visualstudio still doesn't discover the tests.

**Comment by bradwilson** [comment]
Just FYI, support for testing PCLs in Visual Studio has been removed from 2.2, because of the issues related to discovery vs. execution (these problems exist for the devices, too, but I'm not ready to kill support for devices in VS quite yet).

**Comment by JunTaoLuo** [comment]
This issue seems to have been resolved for us, closing.
